name: Meteo Pipeline - Mis à jour chaue 1H

on:
  schedule:
    - cron: '0 * * * *'  
  workflow_dispatch:      

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Cloner le dépôt
      uses: actions/checkout@v3

    - name: Configurer Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Installer les dépendances
      run: |
        pip install -r requirements.txt

    - name: Exécuter le pipeline météo
      run: python pipeline_meteo.py

    - name: Commit & push de la nouvelle base
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add meteo_data.db
        git commit -m " Mise à jour automatique de meteo_data.db via GitHub Actions" || echo "Aucun changement à commit"
        git push
