name: Meteo Pipeline - Mis à jour chaue 1H

on:
  schedule:
    - cron: '0 * * * *'  
  workflow_dispatch:      

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Cloner le dépôt
      uses: actions/checkout@v3

    - name: Configurer Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Installer les dépendances
      run: |
        pip install -r requirements.txt

    - name: Exécuter le pipeline météo
      run: python pipeline_meteo.py

    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        persist-credentials: false  # Utiliser ton PAT à la place du GITHUB_TOKEN
        fetch-depth: 0 

    - name: commit files
      run: |
        git config --local user.name "GitHub Actions"
        git config --local user.email "github-actions@github.com"
        git add meteo_data.db
        git commit -m "Mise à jour automatique de meteo_data.db via GitHub Actions" || echo "Aucun changement à valider"

    - name: Liste des fichiers suivis
      run: git ls-files
        
    - name: push change
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GH_PAT }}
        branch: main
        force: true
