name: Mettre à jour la base météo chaque heure

on:
  schedule:
    - cron: '0 * * * *'  
  workflow_dispatch:      

jobs:
  update-meteo:
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configurer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Installer les dépendances
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Script de mise à jour
        run: python pipeline_meteo.py

      - name: Commit et push de la base mise à jour
        run: |
          git config user.name 'github-actions'
          git config user.email 'github-actions@github.com'
          git add meteo_data.db
          git commit -m "Mise à jour horaire de la base météo" || echo "Rien à commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
