name: Mettre à jour la base météo chaque heure

on:
  schedule:
    - cron: '0 * * * *'  # chaque heure à XX:00
  workflow_dispatch:      # permet de le lancer manuellement aussi

jobs:
  update-meteo:
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v3

      - name: Configurer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Installer les dépendances
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Exécuter le script de mise à jour
        run: python pipeline_meteo.py

      - name: Commit et push de la base mise à jour
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add meteo_data.db
          git commit -m "Mise à jour horaire de la base météo"
          git push
        continue-on-error: true  # ignore l'erreur s'il n'y a pas de changement
